### ISSUE TITLE
Merge Branches

### ISSUE THREAD

**Issue by peeyush14goyal** [coronasafe/arike#104]
Merge below branches into main-tmp. `main-tmp` branch is created for demo to doctors.

- [x] main-visit-details
- [x] treatment
- [x] facility-filter-patients
- [x] schedule

**Comment by khavinshankar** [comment]
@peeyush14goyal `schedule` was already merged to `main` and you forked `main-tmp` from `main`, so `schedule` is also now available on `main-tmp` and it is functional.

I created a seed file and fixed a couple of issues, no it's ready for demo.

**Comment by khavinshankar** [comment]
@peeyush14goyal If all is working fine, we can rename the `main-tmp` branch as `main` and set it as the default

**Comment by peeyush14goyal** [comment]
Merge `main-tmp` to `main` and then testing branches to `main`
