### ISSUE TITLE
💣 User Management Stopped Working

### ISSUE THREAD

**Issue by shrihari689** [coronasafe/arike#13]
Getting this error:
![image](https://user-images.githubusercontent.com/57325503/111957091-94acf580-8b11-11eb-8b15-f22672a97e4f.png)

Since [this commit](https://github.com/coronasafe/arike/commit/93f16b00d740bca81945d10e9ad52156f53327e7), the user role implementation has changed. I think its time to refactor the code.

**Comment by abhinandanarya06** [comment]
Yes i wanted to avoid defining `get_role` function. Let me fix this

**Comment by abhinandanarya06** [comment]
Hmm some of test were not passing because i forget to update role in verify superuser. https://github.com/coronasafe/arike/blob/3a74d87f2caf077986aad91ba99f373464491d83/app/models/user.rb#L44

The form problem fixed please check if working or not

**Comment by shrihari689** [comment]
Yeah. Now it looks good ✅

**Comment by arnabsen1729** [comment]
It is always a good thing to link the commit that fixed the issue. In this case https://github.com/coronasafe/arike/commit/53cd5176f2abfc2fa8a157a695be87148d413ec2 The easiest way is to put the issue number in the commit message. Refer [here](https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message) for more info.
