### ISSUE TITLE
InvalidAuthenticityToken in the deployed application

### ISSUE THREAD

**Issue by arnabsen1729** [coronasafe/arike#16]
## Steps to reproduce
1. Visit https://arike.coronasafe.in/sessions/new
2. Put any user details and press sign in

It will give an error saying `ActionController::InvalidAuthenticityToken in SessionsController#create`

![image](https://user-images.githubusercontent.com/51032928/112090198-23c11880-8bb9-11eb-8b7e-95799a19e130.png)

**Comment by smartclash** [comment]
Did we fix this? I'm still getting this error. I'll probably sit today and try to get this fixed.

**Comment by bodhish** [comment]
@smartclash It looks like the issue is resolved when running the app in production mode.  
http://csn-test.coronasafe.xyz/ (admin user creds in seed) 

Let's reopen this issue if it reappears on production.
