### ISSUE TITLE
ARIKE: To create an interface to capture accurate patient details during 'recurring visits': 1. Current disease status & Patient vitals

### ISSUE THREAD

**Issue by amruthavijay88** [coronasafe/arike#22]
**Current disease status**

1. Patient’s general health status(Pain scale AKPS): 0-100 (0,10,20...100) - (text field - ( Performance scale) (pick from a scale)
2. Any change in disease history? Yes/No + (text field)
3. Palliative phase of illness (dropdown) - (disease scale/status)  - (need to check with dr Athul if it’s for every disease)
   Stable
   Unstable
   Deteriorating
   Dying
 
4. Status in last 7 days (Need to ask Sunitha ma’am on category name)

GENERAL_OPTIONS = Not at all/Slightly/Moderately/Severely/Overwhelmingly/Cannot assess_unconscious
5. Is the patient feeling worried about illness/treatment? (GENERAL_OPTIONS)
6. Does family/friends feel anxious about patient’s illness/treatment (GENERAL_OPTIONS)
7. Is patient depressed (GENERAL_OPTIONS)
8. Has the patient been able to share how he is feeling with his family/friends as much as he wanted:  (GENERAL_OPTIONS)
9. Has the patient had as much information as he wanted (GENERAL_OPTIONS)
10. Do you think patient feels at peace: (GENERAL_OPTIONS)

Diagnosis of patient’s current difficulties: ( Here, please note that for physio - 10,11,12 & 13 are mandatory and other options are optional. For community nurse+secondary nurse+doctors - 15,16,21,22 are mandatory and other options are optional) 

11. Pain (GENERAL_OPTIONS)
12. Shortness of breath (GENERAL_OPTIONS)
13. Weakness/Lack of energy (GENERAL_OPTIONS)
14. Poor mobility (GENERAL_OPTIONS)
15. Nausea (GENERAL_OPTIONS) 
16. Vomiting (GENERAL_OPTIONS)
17. Poor Appetite (GENERAL_OPTIONS)
18. Constipation (GENERAL_OPTIONS)
19. Sore/dry mouth (GENERAL_OPTIONS)
20. Drowsiness (GENERAL_OPTIONS)
21. Wound (GENERAL_OPTIONS)
22. Lack of sleep (GENERAL_OPTIONS)
23. Micturition (GENERAL_OPTIONS)

24. Any other symptoms? - (text area) (optional)

**Physical examination:** 

25. BP (optional)
26. GRBS: (optional)
27. RR: (optional)
28. Pulse: (optional)
29. Personal hygiene: (optional)
30. Mouth hygiene: (optional)
31. Pubic hygiene: (optional)
32. Systemic examination: Cardiovascular/Gastrointestinal/Central nervous system/Respiratory/Genital-urinary -  option - optional field
Systemic examination details: text area
33. Visit done by: Dr/Volunteer/ASHA/Driver - names - text area

**Comment by sam9111** [comment]
- [ ] Create visiting_details table to record every visit
