### ISSUE TITLE
Fix a bug with mimemagic gem

### ISSUE THREAD

**Issue by sam9111** [coronasafe/arike#28]
When i am trying to run a 'bundle install', it fails with an error like below.

```
Fetching gem metadata from https://rubygems.org/...........
Your bundle is locked to mimemagic (0.3.2), but that version could not be found in any of the sources listed
in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.2) has removed it.
You'll need to update your bundle to a version other than mimemagic (0.3.2) that hasn't been removed in order
to install.
```

**Comment by sam9111** [comment]
I have resolved this by updating mimemagic in Gemfile.lock to 0.3.9.

https://github.com/rails/rails/issues/41757

**Comment by shrihari689** [comment]
## For Windows Users 😁

I ran into this error 👇👇
```
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml",
"/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.
```

I searched for `freedesktop.org.xml` and got into [this](https://cgit.freedesktop.org/xdg/shared-mime-info/plain/freedesktop.org.xml.in?h=Release-1-9). I have no idea, what's this. 🤔 
But this file has some license issue itseems.

I just downloaded the file and kept in a separate folder and set it to env variable. 

`set FREEDESKTOP_MIME_TYPES_PATH=<path of the file>`
and then `bundle install`

It worked 🤐🎉

**Comment by bodhish** [comment]
This issue is now resolved
