### ISSUE TITLE
ARIKE: Password reset

### ISSUE THREAD

**Issue by amruthavijay88** [coronasafe/arike#35]
**Is your feature request related to a problem? Please describe.**
Currently the password reset option allows the user to reset password via sending code via sms or via email. 

**Describe the solution you'd like**
We need to keep it to just email, as sending message over mobile will cost us much more. During phase 1 of the project, let's just keep email as an option - for sending code.

**Comment by shrihari689** [comment]
## Proposed Changes ⏰

- Delete `options` template file 💡
- Route to `send_otp via email` ⚡

Task Completed via 2bef74b ✅

**Comment by shrihari689** [comment]
Again Moving to `Reset Link` method since we don't have mobile option 📍📌
Following here #52 🚁

**Comment by shrihari689** [comment]
Completed as of #59 📌
