### ISSUE TITLE
User Device Gem for user session management

### ISSUE THREAD

**Issue by bodhish** [coronasafe/arike#44]
The device gem comes with a lot of integrations that could be used for proper user session management. 

https://github.com/heartcombo/devise

**Comment by shrihari689** [comment]
Todo List 📃:

- [ ] Create a branch
- [ ] Add the Gem and Install
- [ ] Setup Controller Actions
- [ ] Setup Routes
- [ ] Configure the models
- [ ] Migrate to DB if any

@smartclash @shaileshaanand
