### ISSUE TITLE
Create `states` and `districts` tables.

### ISSUE THREAD

**Issue by ProCode2** [coronasafe/arike#57]
**Is your feature request related to a problem? Please describe.**
Currently, we are using strings (`"Kerala"`) in `state` and `district` fields everywhere.

**Describe the solution you'd like**
Make `states` and `districts` tables and use references to specific records of this table instead of using strings.

**Additional Information**
fields the tables will have (**for now**):
#### **State**
    name : string

#### **District**
    name : string
    states_id : uuid

#### **LSG_BODIES**
- Remove `districts : string` column
- Add `districts_id : uuid` column

**Comment by Apurva-Nagar** [comment]
Created the `states` and `districts `tables.
