### ISSUE TITLE
ARIKE: To create push scale for wounds

### ISSUE THREAD

**Issue by amruthavijay88** [coronasafe/arike#65]
**Is your feature request related to a problem? Please describe.**
To enable users to calculate 'PUSH SCALE' factor for wounds

This has to be available when an official chooses wound category - under physical examinations

**Additional context**
[Evaluation example](https://drive.google.com/file/d/1-i9nKDsXAy9Z-d5tlx6R6tTPNehbqXgH/view?usp=sharing)

**Comment by ProCode2** [comment]
Push scale components is created, People working on the long-form just need to integrate it now, Closing this issue.
