### ISSUE TITLE
ARIKE: Categorizing "Treatment procedures"

### ISSUE THREAD

**Issue by amruthavijay88** [coronasafe/arike#66]
**Is your feature request related to a problem? Please describe.**
Right now Treatment procedures look too long, we need to segregate it in the below categories -

**General care -** 
Mouth care
Bath
Nail cutting
Shaving

**Genito urinary care**
Perennial care
Condom catheterisation & training
Nelcath catheterisation & training 
Foley’s catheterisation 
Foley’s catheter care
Suprapubic catheterisation 
Suprapubic catheter care
Bladder wash with normal saline
Bladder wash with soda bicarbonate 
Urostomy care

**Gastro-intestinal care**
Ryles tube insertion
Ryles tube care
Ryles tube feeding & training
PEG care
Per Rectal Enema
High enema
Bisacodyl Suppository
Digital evacuation 
Colostomy care
Colostomy irrigation care
ileostomy care

**Wound care** 
Wound care training given to family
Wound dressing
Suture removal 
Vacuum dressing

**Respiratory care**
Tracheostomy care
Chest physiotherapy
Inhaler training 
Oxygen concentrator - training
Bi-PAP training
Bandaging
Upper limb lymphedema bandaging
Lower limb lymphedema bandaging
Upper limb lymphedema hosiery
PVOD bandaging

**Invasive care**
IV fluid infusion
IV medicine bolus administration 
IV cannula care 
IV cannula insertion
S/C cannula insertion
S/C fluid infusion (subcutaneous)
S/C medicine bolus administration 
S/C cannula care
Ascites tapping
Ascitic catheter care

**Physiotherapy**
Passive Movement
Active Movement
Strengthening exercises
NDT
GAIT Training
Modalities + text field
Breathing exercises
Balance & Coordination exercises
Stretching
Postural correction

**Comment by Azura696** [comment]
Organizing treatment procedures into categories, like 'General Care,' '[Colostomy](https://colomajic.com/product-category/reusable-colostomy-pouch/) Care,' 'Wound Care,' and others, can improve efficiency and help healthcare professionals access the information they need quickly. This simplifies the process for both caregivers and patients
