### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by peeyush14goyal** [coronasafe/arike#90]
We have to merge the following branches into main:

- [x] improvements @divyagar @Sandra3657 
- [x] main-visit-details @peeyush14goyal **Ready for writing tests**  
- [x] visit-details-view @peeyush14goyal - **This branch is a subbranch of new-view-status** 
- [x] treatment  @Sandra3657- **Created PR** PR #92 
- [x] patient-rescript @divyagar - **This branch is already merged in main**
- [x] disease-history @divyagar - **This branch is already merged in main**
- [x] new-view-status - @peeyush14goyal - **This branch is a subbranch of main-visit-details** 
- [ ] rescript-dropdown
- [x] schedule - **This branch is already merged in main**
- [x] dashboard - **This branch is already merged in main**
- [x] facility - **This branch is already merged in main**
- [x] wire-password-reset - **This branch is already merged in main**

Pickup branches in this order. I know the code about Patient Management so you can skip those. Once completed along with writing tests create a PR

**Integration Testing** 
Reference Files: https://github.com/pupilfirst/pupilfirst/blob/master/spec/system/submissions/review_spec.rb
https://github.com/pupilfirst/pupilfirst/blob/master/spec/system/courses/review_spec.rb

- [x] treatment - @Sandra3657 
- [ ] Users Signup - @divyagar 
- [ ] Facilities - @ProCode2, @Sandra3657 
- [x] Patients - @peeyush14goyal 

**Ideas**

 
**Pending**
Account Settings
Schedule
Calendar

**Comment by peeyush14goyal** [comment]
@sam9111 you can start work on the documentation of the code and features present in the main branch.

**Comment by sam9111** [comment]
> @sam9111 you can start work on the documentation of the code and features present in the main branch.

Yes!
